version: "3"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
     - api_vol:/api
    networks:
     - internal
    restart: on-failure

networks:
  internal:

volumes:
  api_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/arthur/Documents/42/ft_transcendence/api
      o: bind
