version: "3"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
     - ./api:/api
    environment:
      NODE_ENV: development
    #networks:
    # - internal
    restart: on-failure
    command: /api/entrypoint.sh

#networks:
#  internal:

