version: "3"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
     - ./api:/api
    environment:
      NODE_ENV: development
    networks:
     - db_network
     - api_network
    restart: on-failure
    command: /api/entrypoint.sh
    secrets:
      - db_password

  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
     - db_network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

##
# DEBUG CONTAINERS
##
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - db_network
    volumes:
      - ${PGADMIN_PATH}:/var/lib/pgadmin
    ports:
      - "5050:80"
    profiles:
      - debug

networks:
  db_network:
  api_network:

secrets:
  db_password:
    file: ./.db_password.secret
